### ISSUE TITLE
Drag drop api not only for iPad

### ISSUE THREAD

**Issue by milo526** [erenkabakci/WWDC-Recap#1]
[Here](https://github.com/erenkabakci/WWDC17-Recap/blob/master/Keynote/Platforms_State_of_the_Union.Monday.md#drag--drop-ipad-only-for-now) you state that the drag and drop api is currently only available for iPad, while during the introduction talk (for which I can't find the video currently) about this api, they stated that:
1. Drag and drop is supported on iPhone BUT
2. You can only move files within the same api

I think this is a clear distinction which might be emphasised more.

Thank you for this informational repository.

**Comment by erenkabakci** [comment]
Hey ! Thanks for opening the first issue 🎆 🎊 

I must have missed that part. Could you open a PR so we can fix this immediately.

**Comment by erenkabakci** [comment]
I have updated the related file. Please let me know if you find anywhere else that should be improved.
