### ISSUE TITLE
Join forces with WWDC Notes?

### ISSUE THREAD

**Issue by zntfdr** [erenkabakci/WWDC-Recap#7]
Hi @erenkabakci,
this is Federico from [WWDC Notes](https://github.com/FiveStarsBlog/WWDCNotes) and I just stumbled upon your repository 😃

Similar to WWDC-Recap, WWDC Notes is also an open source collection of summaries from all WWDC videos (currently all the way back to 2012!).

So far we've collected notes for over 300 videos and we're 15-people strong: it would be awesome if you could join our efforts there!

All notes are attributed to their writer, with bio and links to the writer github, websites etc. please feel free to have a [look around](https://wwdcnotes.com).

What do you think? Thank you and please let me know 😊

**Comment by erenkabakci** [comment]
Hi 👋 Thanks for reaching out. Sounds good, open source goes stronger with more people, so feel free to reference my notes over there for the necessary part.

**Comment by zntfdr** [comment]
Thank you, I'm currently focusing on WWDC21 (of course 😄), but I will be happy to bring over some of your notes later on (with attributions and everything). 

I will keep you up to date :)

Thank you again
